### ISSUE TITLE
希望加入通过配置文件来配置的选项呐~

### ISSUE THREAD

**Issue by ghost** [FiveYellowMice/curly-turtle#1]
就像Parsoid那样啦：https://www.mediawiki.org/w/index.php?title=Parsoid

**Comment by FiveYellowMice** [comment]
配置文件的功能在昨天晚上的 d943973 加上了，为了方便我就用了 JSON 格式，而且还没来得及写文档。  
我打算改用 YaML 来配置，因为这样用户写起来比较直观。  
不过像 Parsoid 那样是指的什么样？

**Comment by ghost** [comment]
没有，只是给个例子希望用配置文件而已😂😂
