### ISSUE TITLE
在麦当劳WIFI用笔记本的虚拟机在AWS注册个主机设置放上去就可以公开了

### ISSUE THREAD

**Issue by ntgeralt** [FiveYellowMice/curly-turtle#4]
看你写的那么长“不得已的妥协”，来‘吐槽’一下你而已。AWS 1年免费，买个8元1美刀虚拟信用卡+4元pin接听即可搭建。

**Comment by FiveYellowMice** [comment]
谢谢建议，但是还是不可以啊，我不提供服务的原因，总结起来就俩：
1. 被五毛知道了，会被封。
2. 被封了，我人会被查水表。

用 AWS 不能解决上述任何一个问题。

**Comment by ntgeralt** [comment]
我之所以说用麦当劳wifi注册aws，而不是在自己家里用自己邮箱注册aws，就是解决第二个问题囖。第一个问题解决方法是，封了东京主机，aws还有其余5个地区主机可以开来用。不过这是纯粹专注公益事业的做法，普通的话分享给熟人就够了。

**Comment by FiveYellowMice** [comment]
在麦当劳注册不能够达到匿名啊，还是会知道在哪个城市，一样会产生金钱交易。还有我搞出来了以后怎么传播出去？要是看出这是 Curly Turtle 十有八九的人会猜出这是我……
唉，所以难度太大了，这公益做不起。

**Comment by ntgeralt** [comment]
哈哈，看你那么耐心回复赞一个。
